"""initial schema: users, events, event_roles, sessions, invitations

Revision ID: 0001
Revises:
Create Date: 2025-01-01

Hand-written (not autogenerated) so the role_enum type is created before
the event_roles table that depends on it.
"""

from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # 1. USERS — api_token is a plaintext opaque bearer token (see TRADEOFFS.md).
    op.execute(
        """
        CREATE TABLE users (
            id         SERIAL PRIMARY KEY,
            email      VARCHAR(255) NOT NULL UNIQUE,
            name       VARCHAR(255) NOT NULL,
            api_token  VARCHAR(255) NOT NULL
        );
        """
    )
    # Option B: one named unique B-tree index (the constraint-free form of UNIQUE).
    op.execute("CREATE UNIQUE INDEX idx_users_api_token ON users (api_token);")

    # 2. EVENTS — timezone is IANA (e.g. 'America/New_York') for event-local time.
    op.execute(
        """
        CREATE TABLE events (
            id          SERIAL PRIMARY KEY,
            title       VARCHAR(255) NOT NULL,
            description TEXT,
            timezone    VARCHAR(64) NOT NULL DEFAULT 'UTC',
            created_at  TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
        );
        """
    )

    # 3. EVENT_ROLES — the authorization chokepoint source of truth.
    op.execute("CREATE TYPE role_enum AS ENUM ('ADMIN', 'CONTRIBUTOR', 'ATTENDEE');")
    op.execute(
        """
        CREATE TABLE event_roles (
            id       SERIAL PRIMARY KEY,
            user_id  INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            event_id INT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
            role     role_enum NOT NULL
        );
        """
    )
    op.execute(
        "CREATE UNIQUE INDEX idx_user_event ON event_roles (user_id, event_id);"
    )

    # 4. SESSIONS — room_name is a string; end_time + room/time index support
    #    the "is this room free for N minutes?" query the agent relies on.
    op.execute(
        """
        CREATE TABLE sessions (
            id         SERIAL PRIMARY KEY,
            event_id   INT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
            title      VARCHAR(255) NOT NULL,
            room_name  VARCHAR(255) NOT NULL,
            start_time TIMESTAMPTZ NOT NULL,
            end_time   TIMESTAMPTZ NOT NULL,
            CONSTRAINT sessions_time_order CHECK (end_time > start_time)
        );
        """
    )
    op.execute("CREATE INDEX idx_sessions_event_id ON sessions (event_id);")
    op.execute(
        "CREATE INDEX idx_sessions_room_time ON sessions (room_name, start_time, end_time);"
    )

    # 5. INVITATIONS — 50k scale; composite + unique indexes for keyset pagination
    #    and retry-safe bulk invites.
    op.execute(
        """
        CREATE TABLE invitations (
            id         SERIAL PRIMARY KEY,
            event_id   INT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
            email      VARCHAR(255) NOT NULL,
            status     VARCHAR(50) DEFAULT 'PENDING' NOT NULL,
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
        );
        """
    )
    op.execute(
        "CREATE INDEX idx_invitations_event_id_id ON invitations (event_id, id);"
    )
    op.execute("CREATE INDEX idx_invitations_email ON invitations (email);")
    op.execute(
        "CREATE UNIQUE INDEX idx_invitations_event_email ON invitations (event_id, email);"
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS invitations;")
    op.execute("DROP TABLE IF EXISTS sessions;")
    op.execute("DROP TABLE IF EXISTS event_roles;")
    op.execute("DROP TYPE IF EXISTS role_enum;")
    op.execute("DROP TABLE IF EXISTS events;")
    op.execute("DROP TABLE IF EXISTS users;")
